[project]
site_name = "Emploi Nouvelle-Calédonie"
site_url = "https://adriens.github.io/emploi-nc/"
site_description = "Offres d'emploi déposées sur le site Emploi NC"
site_author = "Adrien"

[theme]
name = "zensical"

[[theme.palette]]
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[theme.palette]]
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[extra.social]]
icon = "fontawesome/solid/briefcase"
link = "https://emploi.nc/"
name = "Site officiel Emploi.nc"

[[extra.social]]
icon = "fontawesome/solid/database"
link = "https://data.gouv.nc/explore/dataset/offres-d-emploi-deposees-sur-le-site-emploi-nc"
name = "Source Open Data"
